package com.xstd.pirvatephone.dao.model;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODEL.
 */
public class Model implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String model_name;
    private Integer model_type;

    public Model() {
    }

    public Model(Long id) {
        this.id = id;
    }

    public Model(Long id, String model_name, Integer model_type) {
        this.id = id;
        this.model_name = model_name;
        this.model_type = model_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getModel_name() {
        return model_name;
    }

    public void setModel_name(String model_name) {
        this.model_name = model_name;
    }

    public Integer getModel_type() {
        return model_type;
    }

    public void setModel_type(Integer model_type) {
        this.model_type = model_type;
    }

    @Override
    public String toString() {
        return "[Model]" + "id = " + id + ", " + "model_name = " + model_name + ", " + "model_type = " + model_type + "\r\n";
    }

}
