package com.xstd.pirvatephone.dao.phone;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.phone.phone_record;
import com.xstd.pirvatephone.dao.phone.phone_detail;

import com.xstd.pirvatephone.dao.phone.phone_recordDao;
import com.xstd.pirvatephone.dao.phone.phone_detailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phone_recordDaoConfig;
    private final DaoConfig phone_detailDaoConfig;

    private final phone_recordDao phone_recordDao;
    private final phone_detailDao phone_detailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phone_recordDaoConfig = daoConfigMap.get(phone_recordDao.class).clone();
        phone_recordDaoConfig.initIdentityScope(type);

        phone_detailDaoConfig = daoConfigMap.get(phone_detailDao.class).clone();
        phone_detailDaoConfig.initIdentityScope(type);

        phone_recordDao = new phone_recordDao(phone_recordDaoConfig, this);
        phone_detailDao = new phone_detailDao(phone_detailDaoConfig, this);

        registerDao(phone_record.class, phone_recordDao);
        registerDao(phone_detail.class, phone_detailDao);
    }
    
    public void clear() {
        phone_recordDaoConfig.getIdentityScope().clear();
        phone_detailDaoConfig.getIdentityScope().clear();
    }

    public phone_recordDao getPhone_recordDao() {
        return phone_recordDao;
    }

    public phone_detailDao getPhone_detailDao() {
        return phone_detailDao;
    }

}
