package com.xstd.pirvatephone.dao.phone;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHONE_DETAIL.
 */
public class PhoneDetail implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String phone_number;
    private String name;
    private Integer type;
    private Long date;
    private Long duration;

    public PhoneDetail() {
    }

    public PhoneDetail(Long id) {
        this.id = id;
    }

    public PhoneDetail(Long id, String phone_number, String name, Integer type, Long date, Long duration) {
        this.id = id;
        this.phone_number = phone_number;
        this.name = name;
        this.type = type;
        this.date = date;
        this.duration = duration;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    @Override
    public String toString() {
        return "[PhoneDetail]" + "id = " + id + ", " + "phone_number = " + phone_number + ", " + "name = " + name + ", " + "type = " + type + ", " + "date = " + date + ", " + "duration = " + duration + "\r\n";
    }

}
