package com.xstd.pirvatephone.dao.phone;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHONE_RECORD.
 */
public class phone_record implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private Long phone_number;
    private Integer type;
    private Integer count;
    private Long start_time;

    public phone_record() {
    }

    public phone_record(Long id) {
        this.id = id;
    }

    public phone_record(Long id, Long phone_number, Integer type, Integer count, Long start_time) {
        this.id = id;
        this.phone_number = phone_number;
        this.type = type;
        this.count = count;
        this.start_time = start_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(Long phone_number) {
        this.phone_number = phone_number;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getStart_time() {
        return start_time;
    }

    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }

    @Override
    public String toString() {
        return "[phone_record]" + "id = " + id + ", " + "phone_number = " + phone_number + ", " + "type = " + type + ", " + "count = " + count + ", " + "start_time = " + start_time + "\r\n";
    }

}
