package com.xstd.pirvatephone.dao.phone;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHONE_DETAIL.
 */
public class phone_detail implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private Long phone_number;
    private Integer type;
    private Long start_time;
    private Long end_time;

    public phone_detail() {
    }

    public phone_detail(Long id) {
        this.id = id;
    }

    public phone_detail(Long id, Long phone_number, Integer type, Long start_time, Long end_time) {
        this.id = id;
        this.phone_number = phone_number;
        this.type = type;
        this.start_time = start_time;
        this.end_time = end_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(Long phone_number) {
        this.phone_number = phone_number;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getStart_time() {
        return start_time;
    }

    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }

    public Long getEnd_time() {
        return end_time;
    }

    public void setEnd_time(Long end_time) {
        this.end_time = end_time;
    }

    @Override
    public String toString() {
        return "[phone_detail]" + "id = " + id + ", " + "phone_number = " + phone_number + ", " + "type = " + type + ", " + "start_time = " + start_time + ", " + "end_time = " + end_time + "\r\n";
    }

}
