package com.xstd.pirvatephone.dao.phone;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.phone.phone_detail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PHONE_DETAIL.
*/
public class phone_detailDao extends AbstractDao<phone_detail, Long> {

    public static final String TABLENAME = "PHONE_DETAIL";

    /**
     * Properties of entity phone_detail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Phone_number = new Property(1, Long.class, "phone_number", false, "PHONE_NUMBER");
        public final static Property Type = new Property(2, Integer.class, "type", false, "TYPE");
        public final static Property Start_time = new Property(3, Long.class, "start_time", false, "START_TIME");
        public final static Property End_time = new Property(4, Long.class, "end_time", false, "END_TIME");
    };


    public phone_detailDao(DaoConfig config) {
        super(config);
    }
    
    public phone_detailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PHONE_DETAIL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PHONE_NUMBER' INTEGER," + // 1: phone_number
                "'TYPE' INTEGER," + // 2: type
                "'START_TIME' INTEGER," + // 3: start_time
                "'END_TIME' INTEGER);"); // 4: end_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PHONE_DETAIL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, phone_detail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long phone_number = entity.getPhone_number();
        if (phone_number != null) {
            stmt.bindLong(2, phone_number);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, type);
        }
 
        Long start_time = entity.getStart_time();
        if (start_time != null) {
            stmt.bindLong(4, start_time);
        }
 
        Long end_time = entity.getEnd_time();
        if (end_time != null) {
            stmt.bindLong(5, end_time);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public phone_detail readEntity(Cursor cursor, int offset) {
        phone_detail entity = new phone_detail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // phone_number
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // start_time
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // end_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, phone_detail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPhone_number(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setStart_time(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setEnd_time(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(phone_detail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(phone_detail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
