package com.xstd.pirvatephone.dao.contextmodel;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTEXT_MODEL.
 */
public class ContextModel implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String name;
    private String model_type;

    public ContextModel() {
    }

    public ContextModel(Long id) {
        this.id = id;
    }

    public ContextModel(Long id, String name, String model_type) {
        this.id = id;
        this.name = name;
        this.model_type = model_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getModel_type() {
        return model_type;
    }

    public void setModel_type(String model_type) {
        this.model_type = model_type;
    }

    @Override
    public String toString() {
        return "[ContextModel]" + "id = " + id + ", " + "name = " + name + ", " + "model_type = " + model_type + "\r\n";
    }

}
