package com.xstd.pirvatephone.dao.contextmodel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.contextmodel.ContextModel;

import com.xstd.pirvatephone.dao.contextmodel.ContextModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contextModelDaoConfig;

    private final ContextModelDao contextModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contextModelDaoConfig = daoConfigMap.get(ContextModelDao.class).clone();
        contextModelDaoConfig.initIdentityScope(type);

        contextModelDao = new ContextModelDao(contextModelDaoConfig, this);

        registerDao(ContextModel.class, contextModelDao);
    }
    
    public void clear() {
        contextModelDaoConfig.getIdentityScope().clear();
    }

    public ContextModelDao getContextModelDao() {
        return contextModelDao;
    }

}
