package com.xstd.pirvatephone.dao.demo;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUSH_USER_INFO.
 */
public class PushUserInfo implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private Long lastLoginTime;
    private String generateId;
    private String ticket;
    private String secret_key;
    private String server;

    public PushUserInfo() {
    }

    public PushUserInfo(Long id) {
        this.id = id;
    }

    public PushUserInfo(Long id, Long lastLoginTime, String generateId, String ticket, String secret_key, String server) {
        this.id = id;
        this.lastLoginTime = lastLoginTime;
        this.generateId = generateId;
        this.ticket = ticket;
        this.secret_key = secret_key;
        this.server = server;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public String getGenerateId() {
        return generateId;
    }

    public void setGenerateId(String generateId) {
        this.generateId = generateId;
    }

    public String getTicket() {
        return ticket;
    }

    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    public String getSecret_key() {
        return secret_key;
    }

    public void setSecret_key(String secret_key) {
        this.secret_key = secret_key;
    }

    public String getServer() {
        return server;
    }

    public void setServer(String server) {
        this.server = server;
    }

    @Override
    public String toString() {
        return "[PushUserInfo]" + "id = " + id + ", " + "lastLoginTime = " + lastLoginTime + ", " + "generateId = " + generateId + ", " + "ticket = " + ticket + ", " + "secret_key = " + secret_key + ", " + "server = " + server + "\r\n";
    }

}
