package com.xstd.pirvatephone.dao.contact;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT_INFO.
 */
public class ContactInfo implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    /** Not-null value. */
    private String phone_number;
    /** Not-null value. */
    private String display_name;
    private Long icon_id;
    private int type;

    public ContactInfo() {
    }

    public ContactInfo(Long id) {
        this.id = id;
    }

    public ContactInfo(Long id, String phone_number, String display_name, Long icon_id, int type) {
        this.id = id;
        this.phone_number = phone_number;
        this.display_name = display_name;
        this.icon_id = icon_id;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone_number() {
        return phone_number;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    /** Not-null value. */
    public String getDisplay_name() {
        return display_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

    public Long getIcon_id() {
        return icon_id;
    }

    public void setIcon_id(Long icon_id) {
        this.icon_id = icon_id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "[ContactInfo]" + "id = " + id + ", " + "phone_number = " + phone_number + ", " + "display_name = " + display_name + ", " + "icon_id = " + icon_id + ", " + "type = " + type + "\r\n";
    }

}
