package com.xstd.pirvatephone.dao.contact;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT_INFO.
 */
public class ContactInfo implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String phone_number;
    private String display_name;

    public ContactInfo() {
    }

    public ContactInfo(Long id) {
        this.id = id;
    }

    public ContactInfo(Long id, String phone_number, String display_name) {
        this.id = id;
        this.phone_number = phone_number;
        this.display_name = display_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public String getDisplay_name() {
        return display_name;
    }

    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

    @Override
    public String toString() {
        return "[ContactInfo]" + "id = " + id + ", " + "phone_number = " + phone_number + ", " + "display_name = " + display_name + "\r\n";
    }

}
