package com.xstd.pirvatephone.dao.sms;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.sms.SmsRecord;
import com.xstd.pirvatephone.dao.sms.SmsDetail;

import com.xstd.pirvatephone.dao.sms.SmsRecordDao;
import com.xstd.pirvatephone.dao.sms.SmsDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig smsRecordDaoConfig;
    private final DaoConfig smsDetailDaoConfig;

    private final SmsRecordDao smsRecordDao;
    private final SmsDetailDao smsDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        smsRecordDaoConfig = daoConfigMap.get(SmsRecordDao.class).clone();
        smsRecordDaoConfig.initIdentityScope(type);

        smsDetailDaoConfig = daoConfigMap.get(SmsDetailDao.class).clone();
        smsDetailDaoConfig.initIdentityScope(type);

        smsRecordDao = new SmsRecordDao(smsRecordDaoConfig, this);
        smsDetailDao = new SmsDetailDao(smsDetailDaoConfig, this);

        registerDao(SmsRecord.class, smsRecordDao);
        registerDao(SmsDetail.class, smsDetailDao);
    }
    
    public void clear() {
        smsRecordDaoConfig.getIdentityScope().clear();
        smsDetailDaoConfig.getIdentityScope().clear();
    }

    public SmsRecordDao getSmsRecordDao() {
        return smsRecordDao;
    }

    public SmsDetailDao getSmsDetailDao() {
        return smsDetailDao;
    }

}
