package com.xstd.pirvatephone.dao.sms;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMS_RECORD.
 */
public class SmsRecord implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String phone_number;
    private Long lasted_contact;
    private String lasted_data;
    private Integer count;

    public SmsRecord() {
    }

    public SmsRecord(Long id) {
        this.id = id;
    }

    public SmsRecord(Long id, String phone_number, Long lasted_contact, String lasted_data, Integer count) {
        this.id = id;
        this.phone_number = phone_number;
        this.lasted_contact = lasted_contact;
        this.lasted_data = lasted_data;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    public Long getLasted_contact() {
        return lasted_contact;
    }

    public void setLasted_contact(Long lasted_contact) {
        this.lasted_contact = lasted_contact;
    }

    public String getLasted_data() {
        return lasted_data;
    }

    public void setLasted_data(String lasted_data) {
        this.lasted_data = lasted_data;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    @Override
    public String toString() {
        return "[SmsRecord]" + "id = " + id + ", " + "phone_number = " + phone_number + ", " + "lasted_contact = " + lasted_contact + ", " + "lasted_data = " + lasted_data + ", " + "count = " + count + "\r\n";
    }

}
