package com.xstd.pirvatephone.dao.privacy;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.privacy.SrcToDestMapping;

import com.xstd.pirvatephone.dao.privacy.SrcToDestMappingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig srcToDestMappingDaoConfig;

    private final SrcToDestMappingDao srcToDestMappingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        srcToDestMappingDaoConfig = daoConfigMap.get(SrcToDestMappingDao.class).clone();
        srcToDestMappingDaoConfig.initIdentityScope(type);

        srcToDestMappingDao = new SrcToDestMappingDao(srcToDestMappingDaoConfig, this);

        registerDao(SrcToDestMapping.class, srcToDestMappingDao);
    }
    
    public void clear() {
        srcToDestMappingDaoConfig.getIdentityScope().clear();
    }

    public SrcToDestMappingDao getSrcToDestMappingDao() {
        return srcToDestMappingDao;
    }

}
