package com.xstd.pirvatephone.dao.privacy;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.privacy.PrivacyFile;
import com.xstd.pirvatephone.dao.privacy.PrivacyPwd;

import com.xstd.pirvatephone.dao.privacy.PrivacyFileDao;
import com.xstd.pirvatephone.dao.privacy.PrivacyPwdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig privacyFileDaoConfig;
    private final DaoConfig privacyPwdDaoConfig;

    private final PrivacyFileDao privacyFileDao;
    private final PrivacyPwdDao privacyPwdDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        privacyFileDaoConfig = daoConfigMap.get(PrivacyFileDao.class).clone();
        privacyFileDaoConfig.initIdentityScope(type);

        privacyPwdDaoConfig = daoConfigMap.get(PrivacyPwdDao.class).clone();
        privacyPwdDaoConfig.initIdentityScope(type);

        privacyFileDao = new PrivacyFileDao(privacyFileDaoConfig, this);
        privacyPwdDao = new PrivacyPwdDao(privacyPwdDaoConfig, this);

        registerDao(PrivacyFile.class, privacyFileDao);
        registerDao(PrivacyPwd.class, privacyPwdDao);
    }
    
    public void clear() {
        privacyFileDaoConfig.getIdentityScope().clear();
        privacyPwdDaoConfig.getIdentityScope().clear();
    }

    public PrivacyFileDao getPrivacyFileDao() {
        return privacyFileDao;
    }

    public PrivacyPwdDao getPrivacyPwdDao() {
        return privacyPwdDao;
    }

}
