package com.xstd.pirvatephone.dao.privacy;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRIVACY_PWD.
 */
public class PrivacyPwd implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    /** Not-null value. */
    private String name;
    private String site;
    private String number;
    /** Not-null value. */
    private String password;

    public PrivacyPwd() {
    }

    public PrivacyPwd(Long id) {
        this.id = id;
    }

    public PrivacyPwd(Long id, String name, String site, String number, String password) {
        this.id = id;
        this.name = name;
        this.site = site;
        this.number = number;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "[PrivacyPwd]" + "id = " + id + ", " + "name = " + name + ", " + "site = " + site + ", " + "number = " + number + ", " + "password = " + password + "\r\n";
    }

}
