package com.xstd.pirvatephone.dao.privacy;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRIVACY_PIC.
 */
public class PrivacyPic implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    /** Not-null value. */
    private String name;

    public PrivacyPic() {
    }

    public PrivacyPic(Long id) {
        this.id = id;
    }

    public PrivacyPic(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "[PrivacyPic]" + "id = " + id + ", " + "name = " + name + "\r\n";
    }

}
