package com.xstd.pirvatephone.dao.privacy;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SRC_TO_DEST_MAPPING.
 */
public class SrcToDestMapping implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    /** Not-null value. */
    private String srcName;
    /** Not-null value. */
    private String destName;
    /** Not-null value. */
    private String srcPath;
    private java.util.Date misstime;
    private Integer type;

    public SrcToDestMapping() {
    }

    public SrcToDestMapping(Long id) {
        this.id = id;
    }

    public SrcToDestMapping(Long id, String srcName, String destName, String srcPath, java.util.Date misstime, Integer type) {
        this.id = id;
        this.srcName = srcName;
        this.destName = destName;
        this.srcPath = srcPath;
        this.misstime = misstime;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSrcName() {
        return srcName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSrcName(String srcName) {
        this.srcName = srcName;
    }

    /** Not-null value. */
    public String getDestName() {
        return destName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDestName(String destName) {
        this.destName = destName;
    }

    /** Not-null value. */
    public String getSrcPath() {
        return srcPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSrcPath(String srcPath) {
        this.srcPath = srcPath;
    }

    public java.util.Date getMisstime() {
        return misstime;
    }

    public void setMisstime(java.util.Date misstime) {
        this.misstime = misstime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "[SrcToDestMapping]" + "id = " + id + ", " + "srcName = " + srcName + ", " + "destName = " + destName + ", " + "srcPath = " + srcPath + ", " + "misstime = " + misstime + ", " + "type = " + type + "\r\n";
    }

}
