package com.xstd.pirvatephone.dao.privacy;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SRC_TO_DEST_MAPPING.
 */
public class SrcToDestMapping implements Serializable {

    private static final long serialVersionUID = 1L;
    
    /** Not-null value. */
    private String srcName;
    private String destName;
    /** Not-null value. */
    private String srcPath;
    private Long misstime;

    public SrcToDestMapping() {
    }

    public SrcToDestMapping(String srcName, String destName, String srcPath, Long misstime) {
        this.srcName = srcName;
        this.destName = destName;
        this.srcPath = srcPath;
        this.misstime = misstime;
    }

    /** Not-null value. */
    public String getSrcName() {
        return srcName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSrcName(String srcName) {
        this.srcName = srcName;
    }

    public String getDestName() {
        return destName;
    }

    public void setDestName(String destName) {
        this.destName = destName;
    }

    /** Not-null value. */
    public String getSrcPath() {
        return srcPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSrcPath(String srcPath) {
        this.srcPath = srcPath;
    }

    public Long getMisstime() {
        return misstime;
    }

    public void setMisstime(Long misstime) {
        this.misstime = misstime;
    }

    @Override
    public String toString() {
        return "[SrcToDestMapping]" + "srcName = " + srcName + ", " + "destName = " + destName + ", " + "srcPath = " + srcPath + ", " + "misstime = " + misstime + "\r\n";
    }

}
