package com.xstd.pirvatephone.dao.modeldetail;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.modeldetail.ModelDetail;

import com.xstd.pirvatephone.dao.modeldetail.ModelDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig modelDetailDaoConfig;

    private final ModelDetailDao modelDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        modelDetailDaoConfig = daoConfigMap.get(ModelDetailDao.class).clone();
        modelDetailDaoConfig.initIdentityScope(type);

        modelDetailDao = new ModelDetailDao(modelDetailDaoConfig, this);

        registerDao(ModelDetail.class, modelDetailDao);
    }
    
    public void clear() {
        modelDetailDaoConfig.getIdentityScope().clear();
    }

    public ModelDetailDao getModelDetailDao() {
        return modelDetailDao;
    }

}
