package com.xstd.pirvatephone.dao.service;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.service.ProxyTalk;
import com.xstd.pirvatephone.dao.service.ProxyTicket;

import com.xstd.pirvatephone.dao.service.ProxyTalkDao;
import com.xstd.pirvatephone.dao.service.ProxyTicketDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig proxyTalkDaoConfig;
    private final DaoConfig proxyTicketDaoConfig;

    private final ProxyTalkDao proxyTalkDao;
    private final ProxyTicketDao proxyTicketDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        proxyTalkDaoConfig = daoConfigMap.get(ProxyTalkDao.class).clone();
        proxyTalkDaoConfig.initIdentityScope(type);

        proxyTicketDaoConfig = daoConfigMap.get(ProxyTicketDao.class).clone();
        proxyTicketDaoConfig.initIdentityScope(type);

        proxyTalkDao = new ProxyTalkDao(proxyTalkDaoConfig, this);
        proxyTicketDao = new ProxyTicketDao(proxyTicketDaoConfig, this);

        registerDao(ProxyTalk.class, proxyTalkDao);
        registerDao(ProxyTicket.class, proxyTicketDao);
    }
    
    public void clear() {
        proxyTalkDaoConfig.getIdentityScope().clear();
        proxyTicketDaoConfig.getIdentityScope().clear();
    }

    public ProxyTalkDao getProxyTalkDao() {
        return proxyTalkDao;
    }

    public ProxyTicketDao getProxyTicketDao() {
        return proxyTicketDao;
    }

}
