package com.xstd.pirvatephone.dao.service;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.pirvatephone.dao.service.ProxyTalk;

import com.xstd.pirvatephone.dao.service.ProxyTalkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig proxyTalkDaoConfig;

    private final ProxyTalkDao proxyTalkDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        proxyTalkDaoConfig = daoConfigMap.get(ProxyTalkDao.class).clone();
        proxyTalkDaoConfig.initIdentityScope(type);

        proxyTalkDao = new ProxyTalkDao(proxyTalkDaoConfig, this);

        registerDao(ProxyTalk.class, proxyTalkDao);
    }
    
    public void clear() {
        proxyTalkDaoConfig.getIdentityScope().clear();
    }

    public ProxyTalkDao getProxyTalkDao() {
        return proxyTalkDao;
    }

}
