package com.xstd.pirvatephone.dao.service;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROXY_TICKET.
 */
public class ProxyTicket implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String cardid;
    private String flightnumber;
    /** Not-null value. */
    private java.util.Date date;
    private String receiver;
    private String address;
    private String phonenumber;
    private String status;

    public ProxyTicket() {
    }

    public ProxyTicket(Long id) {
        this.id = id;
    }

    public ProxyTicket(Long id, String name, String cardid, String flightnumber, java.util.Date date, String receiver, String address, String phonenumber, String status) {
        this.id = id;
        this.name = name;
        this.cardid = cardid;
        this.flightnumber = flightnumber;
        this.date = date;
        this.receiver = receiver;
        this.address = address;
        this.phonenumber = phonenumber;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getCardid() {
        return cardid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    public String getFlightnumber() {
        return flightnumber;
    }

    public void setFlightnumber(String flightnumber) {
        this.flightnumber = flightnumber;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getReceiver() {
        return receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "[ProxyTicket]" + "id = " + id + ", " + "name = " + name + ", " + "cardid = " + cardid + ", " + "flightnumber = " + flightnumber + ", " + "date = " + date + ", " + "receiver = " + receiver + ", " + "address = " + address + ", " + "phonenumber = " + phonenumber + ", " + "status = " + status + "\r\n";
    }

}
