package com.xstd.pirvatephone.dao.simulacomm;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simulateCommDaoConfig;

    private final SimulateCommDao simulateCommDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simulateCommDaoConfig = daoConfigMap.get(SimulateCommDao.class).clone();
        simulateCommDaoConfig.initIdentityScope(type);

        simulateCommDao = new SimulateCommDao(simulateCommDaoConfig, this);

        registerDao(SimulateComm.class, simulateCommDao);
    }
    
    public void clear() {
        simulateCommDaoConfig.getIdentityScope().clear();
    }

    public SimulateCommDao getSimulateCommDao() {
        return simulateCommDao;
    }

}
