package com.xstd.pirvatephone.dao.simulacomm;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SIMULATE_COMM.
 */
public class SimulateComm implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private long phonenumber;
    /** Not-null value. */
    private java.util.Date futuretime;
    private String contemt;
    private Integer type;

    public SimulateComm() {
    }

    public SimulateComm(Long id) {
        this.id = id;
    }

    public SimulateComm(Long id, long phonenumber, java.util.Date futuretime, String contemt, Integer type) {
        this.id = id;
        this.phonenumber = phonenumber;
        this.futuretime = futuretime;
        this.contemt = contemt;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(long phonenumber) {
        this.phonenumber = phonenumber;
    }

    /** Not-null value. */
    public java.util.Date getFuturetime() {
        return futuretime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFuturetime(java.util.Date futuretime) {
        this.futuretime = futuretime;
    }

    public String getContemt() {
        return contemt;
    }

    public void setContemt(String contemt) {
        this.contemt = contemt;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "[SimulateComm]" + "id = " + id + ", " + "phonenumber = " + phonenumber + ", " + "futuretime = " + futuretime + ", " + "contemt = " + contemt + ", " + "type = " + type + "\r\n";
    }

}
